//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALdv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentMkDv
    {
        public int ID { get; set; }
        public int IDdv { get; set; }
        public string Name { get; set; }
        public string E_mail { get; set; }
        public int Stars { get; set; }
        public string Comment { get; set; }
        public string Response { get; set; }
        public string Heading { get; set; }
        public bool Public { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual MegkomnatnyeDveri MegkomnatnyeDveri { get; set; }
    }
}
