//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALdv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furnitura
    {
        public Furnitura()
        {
            this.FotoFyrnituries = new HashSet<FotoFyrnitury>();
        }
    
        public int Id { get; set; }
        public string Nazvanie { get; set; }
        public string Proizvoditel { get; set; }
        public string Strana { get; set; }
        public string Material { get; set; }
        public string Pokrytie { get; set; }
        public string Cvet { get; set; }
        public string TyporazmerCilindra { get; set; }
        public string TypKrepega { get; set; }
        public Nullable<int> RecomendTolschinaDvPolotna { get; set; }
        public string TypPlanki { get; set; }
        public string Megosevoe { get; set; }
        public string DopZapirIznutri { get; set; }
        public int Cena { get; set; }
        public Nullable<int> Skidka { get; set; }
        public Nullable<int> CenaSoSkidkoy { get; set; }
        public string Opisanie { get; set; }
        public bool Publicaciya { get; set; }
        public string TypFurnitury { get; set; }
    
        public virtual ICollection<FotoFyrnitury> FotoFyrnituries { get; set; }
    }
}
