//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALdv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MegkomnatnyeDveri
    {
        public MegkomnatnyeDveri()
        {
            this.CommentMkDvs = new HashSet<CommentMkDv>();
            this.FotoMegkomnDvereys = new HashSet<FotoMegkomnDverey>();
        }
    
        public int Id { get; set; }
        public string Nazvanie { get; set; }
        public string Proizvoditel { get; set; }
        public string Strana { get; set; }
        public string Material { get; set; }
        public string Pokrytie { get; set; }
        public string Karkas { get; set; }
        public Nullable<int> IdColor { get; set; }
        public string TypDveri { get; set; }
        public string VnytrenneeNapolnenie { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public Nullable<int> Skidka { get; set; }
        public Nullable<decimal> CenaSoSkidkoy { get; set; }
        public string Opisanie { get; set; }
        public bool Publicaciya { get; set; }
        public string DopCharacteristics { get; set; }
    
        public virtual ICollection<CommentMkDv> CommentMkDvs { get; set; }
        public virtual ICollection<FotoMegkomnDverey> FotoMegkomnDvereys { get; set; }
        public virtual TableColor TableColor { get; set; }
        public virtual SeoMkDverei SeoMkDverei { get; set; }
    }
}
