//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALdv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableColor
    {
        public TableColor()
        {
            this.MegkomnatnyeDveris = new HashSet<MegkomnatnyeDveri>();
            this.VhodnyeDveris = new HashSet<VhodnyeDveri>();
        }
    
        public int IdColor { get; set; }
        public string NameColor { get; set; }
        public byte[] Image { get; set; }
        public string MimeType { get; set; }
    
        public virtual ICollection<MegkomnatnyeDveri> MegkomnatnyeDveris { get; set; }
        public virtual ICollection<VhodnyeDveri> VhodnyeDveris { get; set; }
    }
}
