//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALdv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableOurWork
    {
        public TableOurWork()
        {
            this.TableFotoOurWorks = new HashSet<TableFotoOurWork>();
        }
    
        public int Id { get; set; }
        public string TextOurWorks { get; set; }
    
        public virtual ICollection<TableFotoOurWork> TableFotoOurWorks { get; set; }
    }
}
