//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALdv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VhodnyeDveri
    {
        public VhodnyeDveri()
        {
            this.FotoVhodnyhDvereys = new HashSet<FotoVhodnyhDverey>();
        }
    
        public int Id { get; set; }
        public string Nazvanie { get; set; }
        public string Proizvoditel { get; set; }
        public string Strana { get; set; }
        public string Cvet { get; set; }
        public string Napolnitel { get; set; }
        public string Yplotnitel { get; set; }
        public Nullable<int> TolschinaMetalla { get; set; }
        public string Furnitura { get; set; }
        public string Petli { get; set; }
        public string OtdelkaSnarugi { get; set; }
        public string OtdelkaVnutri { get; set; }
        public Nullable<int> TolschinaDvPolotna { get; set; }
        public int Cena { get; set; }
        public Nullable<int> Skidka { get; set; }
        public Nullable<int> CenaSoSkidcoy { get; set; }
        public string Opisanie { get; set; }
        public bool Publicaciya { get; set; }
    
        public virtual ICollection<FotoVhodnyhDverey> FotoVhodnyhDvereys { get; set; }
        public virtual SeoVhodnuhDverei SeoVhodnuhDverei { get; set; }
    }
}
